set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

bind-key r source-file ~/.config/tmux/tmux.conf \; display "Reloaded from ~/.tmux.conf"
